# Generated by Django 5.1.2 on 2025-02-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_project', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول'),
        ),
    ]
