# Generated by Django 5.1.2 on 2025-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_setting', models.BooleanField(default=True, verbose_name='تنظیمات اصلی')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس سایت')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='تلفن سایت')),
                ('fax', models.CharField(max_length=200, null=True, verbose_name='فکس سایت')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='ایمیل سایت')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('site_lego', models.ImageField(upload_to='images/site-setting', verbose_name='لوگو سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('about_us', models.TextField(verbose_name='درباره سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
