# Generated by Django 5.1.2 on 2025-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_lego',
            new_name='site_logo',
        ),
    ]
