# Generated by Django 5.1.2 on 2025-03-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerlink',
            old_name='footer_link_box',
            new_name='footerlink',
        ),
    ]
