# Generated by Django 5.1.2 on 2025-04-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_article_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_comments',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
