# Generated by Django 5.1.2 on 2025-04-22 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_alter_article_comments_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article_comments',
            new_name='ArticleComments',
        ),
    ]
