# Generated by Django 5.1.2 on 2025-04-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0012_rename_article_comments_articlecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecomments', verbose_name='نظر والد'),
        ),
    ]
