# Generated by Django 5.1.2 on 2025-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0002_remove_user_mobile_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='متن درباره کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='images/profiles', verbose_name='تصویر کاربر'),
        ),
    ]
