# Generated by Django 5.1.2 on 2025-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0003_user_about_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=40, null=True, upload_to='images/profiles', verbose_name='تصویر کاربر'),
        ),
    ]
